DROP TABLE `regions`;
DROP TABLE `areas`;
DROP TABLE `branches`;
DROP TABLE `centers`;
DROP TABLE `loans`;
DROP TABLE `cachers`;
DROP TABLE `rule_books`;
DROP TABLE `targets`;
DROP TABLE `loan_history`;
DROP TABLE `fees`;
DROP TABLE `applicable_fees`;
DROP TABLE `center_meeting_days`;
DROP TABLE `loan_products`;
DROP TABLE `credit_account_rules`;
DROP TABLE `debit_account_rules`;
ALTER TABLE `accruals` DROP COLUMN `loan_id`;
ALTER TABLE `api_accesses` DROP COLUMN `branch_id`;
ALTER TABLE `attendances` DROP COLUMN `center_id`;
ALTER TABLE `checkers` DROP COLUMN `loan_id`;
ALTER TABLE `client_groups` DROP COLUMN `center_id`;
ALTER TABLE `insurance_policies` DROP COLUMN `loan_id`;
ALTER TABLE `postings` DROP COLUMN `fee_id`;
ALTER TABLE `stock_registers` DROP COLUMN `branch_name`;
ALTER TABLE `stock_registers` DROP COLUMN `branch_id`;
DROP TABLE `transaction_summaries`;