--this script will delete old model from database which have been deleted from application--

delete * from regions;
drop table regions;
delete * from areas;
drop table areas;
delete * from branches;
drop table branches;
delete * from centers;
drop table centers;
delete * from loans;
drop table loans;
delete * from cachers;
drop table cachers;
delete * from rule_books;
drop table rule_books;
delete * from targets;
drop table targets;
delete * from loan_history;
drop table loan_history;
delete * from fees;
drop table fees;
delete * from applicable_fees;
drop table applicable_fees;
delete * from center_meeting_days;
drop table center_meeting_days;
delete * from loan_products;
drop table loan_products;
delete * from credit_account_rules;
drop table credit_account_rules;
delete * from debit_account_rules;
drop table debit_account_rules;
alter table accruals drop column loan_id;
alter table api_accesses drop column branch_id;
alter table attendances drop column center_id;
alter table checkers drop column loan_id;
alter table client_groups drop column center_id;
alter table insurance_policies drop column loan_id;
alter table postings drop column fee_id;
alter table stock_registers drop column branch_name;
alter table stock_registers drop column branch_id;
delete * from transaction_summaries;
drop table transaction_summaries;