---
open_on: 2011-04-01
chart:
  name: Financial Accounting
  chart_type: financial_accounting
  assets:
    - Cash
    - Bank Account
    - Micro Finance Loan
    - Debtors-Mf Loan
    - Bad Debts
  liabilities:
    - Advance for Ewi
  incomes:
    - Interest on Microfinance Loan
    - Service Charges
    - Bad Debts Recover
  expenses:
    - Salaries
    - Rent
    - Interest expense