liabilities:
  - LONG TERM BORROWINGS
  - DEFERRED TAX LIABILITIES (NET)
  - OTHER LONG-TERM LIABILITIES
  - LONG-TERM PROVISIONS
  - SHORT-TERM BORROWINGS
  - TRADE PAYABLES
  - OTHER CURRENT LIABILITIES
  - SHORT TERM PROVISIONS
assets:
  - SHARE CAPITAL
  - RESERVES AND SURPLUS
  - MONEY RECEIVED AGAINST SHARE WARRANTS
  - TANGIBLE ASSETS
  - INTANGIBLE ASSETS
  - CAPITAL WORK-IN-PROGRESS
  - INTANGIBLE ASSETS UNDER DEV.
  - NON-CURRENT INVESTMENTS
  - DEFERRED TAX ASSETS (NET)
  - LONG-TERM LOANS AND ADVANCES
  - OTHER NON-CURRENT ASSETS
  - CURRENT INVESTMENTS
  - INVENTORIES
  - TRADE RECEIVABLES
  - CASH AND CASH EQUIVALENTS
  - SHORT-TERM LOANS AND ADVANCES
  - OTHER CURRENT ASSETS