---
open_on: 2011-04-01
chart:
  name: Financial Accounting
  chart_type: financial_accounting
  assets:
    - Cash
    - Bank account
    - Loans made
    - Debtors
  liabilities:
    - Loans taken
  incomes:
    - Interest income
    - Fee income
  expenses:
    - Salaries
    - Rent
    - Interest expense