---
open_on: 2011-04-01
chart:
  name: Financial Accounting
  chart_type: financial_accounting
  assets:
    - Cash
    - Bank Account
    - Loans Made
    - Debtors
    - Loans Write Off
  liabilities:
    - Loans Advance
  incomes:
    - Interest Income
    - Charges Income
    - Other Income
  expenses:
    - Salaries
    - Rent
    - Interest expense