# EXAMPLE: this is how you define a particular role type and what controllers and actions it can access.
# an "all" under a controller means all actions under that controller are accessible.
# an "all" under a rolename means all controllers and subsequent actions under them are all accessible to that rolename

# <rolename1> :
#   <controller1> :
#     - <action1>
#     - <action2>
#     - <action3>
#   <controller2> :
#     - all
#   <controller3> :
#     - <action1>
#     - <action3>
# <rolename2> : all
      
operator : all
################
administrator :
  home : 
    - all
  browse :
    - all
  admin :
    - all  
  audit_trails:
    - index
    - show
  designations :
    - all
  document_types :
    - all
  documents :
    - all
  lending_products :
    - all
  lendings :
    - index
    - show
  loan_purposes :
    - all
  searches :
    - all  
################
executive :
  home : 
    - all
#  admin :
#    - index
  browse :
    - all	
  attendances :
    - index
    - create
  audit_trails :
    - index
    - show
  biz_locations :
#    - index
#   - show
    - centers_for_selector
  client_groups :
    - all
  client_verifications :
    - all
  clients :
    - index
#    - new
#    - create
    - bulk_entry
    - show
#    - edit
    - update
  new_clients :
    - show
  documents :
    - all
  loan_applications :
    - index
    - show
    - bulk_create_loan_applicant
    - bulk_create
    - list
    - bulk_new
#   - edit
    - update
    - get_param_value
#   - all
#  loan_files :
#    - index
#    - show  
#    - get_data
#    - generate_disbursement_sheet
#    - generate_disbursement_labels
#    - record_loan_file
#    - loan_file_generation
#    - get_param_value
#   - all
  lendings :
#    - all
    - index  
    - create
    - create_repayment_on_lending
    - show
    - update_lending_approve_to_disburse
    - update_lending_new_to_approve
    - new
    - lending_transactions
    - payment_on_disburse_loan
    - lending_due_statuses
    - lending_status_history
  searches :
    - all
  user_locations :
    - all
#  lending_products :
#    - index
#    - show
  reports :
    - all
  payment_transactions :
    - index
    - new
    - weeksheet_payments
    - create_group_payments  
  center_cycles :
    - record_cgt
    - mark_cgt_grt
#    - record_grt     
################    
supervisor :
  home :
    - all	
  browse :
    - all
  admin :
    - index	 
#  asset_register :
#    - index  
#    - new
#    - create
#    - edit
#    - update
#    - show
  attendances :
    - index
    - create
  audit_trails:
    - index
    - show
  biz_locations:
 #   - all
    - create_and_assign_location
    - map_locations
    - show
    - create
#    - index
    - biz_location_clients
    - biz_location_form
    - centers_for_selector    	
  center_cycles :
    - all
  client_groups :
    - all
  client_groups :
    - all
  client_verifications :
    - all
  clients :
    - index
    - new
    - create
    - bulk_entry
    - show
    - edit
    - update
  new_clients :
    - all
  documents :
    - all
  holiday_calendars :
    - all
  holidays :
    - all
  lendings :
    - all 
#    - index  
#    - create
#   - create_repayment_on_lending
#    - show
#    - edit
#    - update
#    - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
#    - new
#    - lending_transactions
#    - payment_on_disburse_loan
#    - lending_due_statuses
  loan_applications :
     - index
     - show
     - bulk_create_loan_applicant
     - bulk_create
     - list 
     - bulk_new
     - edit
     - update
     - get_param_value
     - suspected_duplicates
     - get_de_dupe_loan_applications
     - record_suspected_duplicates
#     - all
  loan_authorizations :
     - all
  loan_files :
     - index
     - show  
     - get_data
     - generate_disbursement_sheet
     - generate_disbursement_labels
     - record_loan_file
     - loan_file_generation
     - get_param_value
     - pending_loan_file_generation
#     - all
#  overlap_report_requests:
#    - all
#  overlap_report_responses:
#    - all  
  user_locations :
    - all  
  searches :
    - all
#  lending_products :
#    - index
#    - show
  reports :
    - show
    - create
    - edit
 #   - all
  center_cycles :
    - record_cgt
    - mark_cgt_grt
    - record_grt
  payment_transactions :
    - index
    - new
    - weeksheet_payments
    - create_group_payments
 # book_keeping :
 #   - all
 # ledgers :
 #   - all
  money_deposits :
     - index
     - create
#     - mark_verification
#     - record_verification
     - get_bank_branches
     - get_bank_accounts  
#################
support :
  admin :
    - index
    - show
  home : 
    - all
  browse :
    - all
  accounting_rules :
    - index
    - show
  asset_register :
#     - all		 
    - index  
    - new
    - create
    - edit
    - update
    - show
    
  attendances :
    - index
    - create
  audit_trails:
    - all
    - index
    - show
  book_keeping :
    - all
  center_cycles :
    - all
  client_groups :
    - all
  client_verifications :
    - all
  clients :
    - index
    - new
    - create
    - bulk_entry
    - show
#  documents :
#    - all
#  holiday_calendars :
#    - all
#  ledgers :
#    - index
#   - show
  lendings :
    - index  
    - create
    - create_repayment_on_lending
    - show
    - edit
    - update
    - update_lending_approve_to_disburse
    - update_lending_new_to_approve
  loan_applications :
    - index
    - show
#   - bulk_create_loan_applicant
#   - bulk_create
    - list
    - bulk_new
#   - edit
    - update
    - get_param_value
    - suspected_duplicates
    - get_de_dupe_loan_applications
    - record_suspected_duplicates
#   - all
  loan_files :
    - index
    - show  
    - get_data
    - generate_disbursement_sheet
    - generate_disbursement_labels
#   - record_loan_file
#   - loan_file_generation
    - get_param_value
#   - all
  reports :
#    - index
    - show
    - get_dates
    - get_date   
  searches :
    - all
  user_locations :
    - all
  biz_locations :
    - centers_for_selector  
################    
finops :
  home : 
    - all
  browse :
    - all
  accounting_rules :
    - all
    - index
    - show
  ledgers :
    - all
  asset_register :
    - index  
    - new
    - create
    - edit
    - update
    - show
#  attendances :
#    - index
#    - create
  audit_trails :
    - index
    - show
  biz_locations :
#    - index
#    - create
#    - edit
#    - update
#    - show
    - centers_for_selector
  book_keeping :
    - all
#  center_cycles :
#    - all
  client_groups :
    - all
#  client_verifications :
#    - all
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
#    - edit
    - update
  designations :
    - all
  document_types :
    - all
  documents :
    - all  
  funders :
    - all  
  funding_lines :
    - all
#  ledgers :
#    - index
#    - show
  lending_products :
    - all
  lendings :
    - index  
    - create
    - create_repayment_on_lending
    - show
    - edit
    - update
  loan_applications :
    - index
    - show
#   - bulk_create_loan_applicant
#   - bulk_create
    - list
#    - bulk_new
    - edit
    - update
    - get_param_value
    - suspected_duplicates
    - get_de_dupe_loan_applications
    - record_suspected_duplicates
#  loan_applications :
#    - all
#    - edit
#    - update
  overlap_report_requests:
    - all
  overlap_report_responses:
    - all 
  loan_purposes :
    - all
  searches :
    - all  
  loan_files :
#    - index
    - show  
#    - get_data
    - generate_disbursement_sheet
    - generate_disbursement_labels
#    - record_loan_file
#    - loan_file_generation
    - get_param_value
    - record_health_check_status
    - generate_loans
#  loan_authorizations :
#    - all
  reports :
#    - all 
#    - index
    - show
    - get_dates
    - get_date
  center_cycles :
    - record_cgt
    - mark_cgt_grt
#    - record_grt 
  user_locations :
    - all
  money_deposits :
     - index
#     - create
     - mark_verification
     - record_verification
#     - get_bank_branches
#     - get_bank_accounts  
################        
read_only :
  home : 
    - all
  browse :
    - all
#  accounting_rules :
#    - index
#    - show
#  asset_register :
#     - all		 
#    - index  
#    - new
#    - create
#    - edit
#    - update
#    - show
    
#  attendances :
#    - index
#    - create
#  audit_trails:
#    - all
#    - index
#    - show
#  biz_locations:
#    - all    
#  book_keeping :
#    - all
#  center_cycles :
#    - all
#  client_groups :
#    - all
#  client_verifications :
#    - all
  new_clients :
    - show  
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
  user_locations :
    - all
#  documents :
#    - all
#  holiday_calendars :
#    - all
#  ledgers :
#    - index
#   - show
  lendings :
    - index  
  
#    - create
#    - create_repayment_on_lending
    - show
#    - edit
#    - update
#   - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
    - lending_accrual_transaction
#  loan_applications :
#   - index
#    - show
#   - bulk_create_loan_applicant
#   - bulk_create
#    - list
#    - bulk_new
#   - edit
#    - update
#    - get_param_value
#    - suspected_duplicates
#    - get_de_dupe_loan_applications
#    - record_suspected_duplicates
#   - all
#  loan_files :
#    - index
#    - show  
#    - get_data
#    - generate_disbursement_sheet
#    - generate_disbursement_labels
#   - record_loan_file
#   - loan_file_generation
#    - get_param_value
#   - all
  reports :
#    - index
#    - show
#    - get_dates
#    - get_date   
#  searches :
#    - all
accountant : all
auditor : all