# EXAMPLE: this is how you define a particular role type and what controllers and actions it can access.
# an "all" under a controller means all actions under that controller are accessible.
# an "all" under a rolename means all controllers and subsequent actions under them are all accessible to that rolename

# <rolename1> :
#   <controller1> :
#     - <action1>
#     - <action2>
#     - <action3>
#   <controller2> :
#     - all
#   <controller3> :
#     - <action1>
#     - <action3>
# <rolename2> : all

operator : all

administrator :
  home :
    - all
  browse :
    - all
  admin :
    - all
  audit_trails:
    - index
    - show
  designations :
    - all
  document_types :
    - all
  documents :
    - all
  lending_products :
    - all
  lendings :
    - index
    - show
  loan_purposes :
    - all
  searches :
    - all
################
executive :
  home :
    - all
#  admin :
#    - index
  browse :
    - all
  attendances :
    - index
    - create
  staff_attendances :
  audit_trails :
    - index
    - show
  biz_locations :
#    - index
#   - show
    - centers_for_selector
  client_groups :
    - all
  client_verifications :
    - all
  clients :
    - index
    - new
    - create
    - bulk_entry
    - show
#    - edit
    - update
  new_clients :
    - show
    - new
    - create
    - edit
    - update
#    - register_death_event
#    - record_death_event
    - client_insurance_policies
  documents :
    - all
  loan_applications :
    - index
    - show
    - bulk_create_loan_applicant
    - bulk_create
    - list
    - bulk_new
#   - edit
    - update
    - get_param_value
#   - all
#  loan_files :
#    - index
#    - show
#    - get_data
#    - generate_disbursement_sheet
#    - generate_disbursement_labels
#    - record_loan_file
#    - loan_file_generation
#    - get_param_value
#   - all
  lendings :
#    - all
    - index
    - create
    - create_repayment_on_lending
    - show
    - update_lending_approve_to_disburse
    - update_lending_new_to_approve
    - new
    - lending_transactions
    - payment_on_disburse_loan
    - lending_due_statuses
    - lending_status_history
    - lending_preclose
    - check_preclosure_date
    - record_lending_preclose
    - save_lendings_fee
  searches :
    - all
  user_locations :
    - all
  lending_products :
    - index
    - show
    - create
  reports :
    - all
  fee_instances :
     - fee_instance_on_lending
     - index
  payment_transactions :
    - index
    - new
    - weeksheet_payments
    - create_group_payments
    - payment_form_for_lending
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
#    - all
  center_cycles :
    - record_cgt
    - mark_cgt_grt
#    - record_grt
################
supervisor :
  home :
    - all
  browse :
    - all
  admin :
    - index
#  asset_register :
#    - index
#    - new
#    - create
#    - edit
#    - update
#    - show
  staff_attendances :
    - create
  attendances :
    - index
    - create
  audit_trails:
    - index
    - show
  biz_locations:
 #   - all
    - create_and_assign_location
    - map_locations
    - show
    - create
#    - index
    - biz_location_clients
    - biz_location_form
    - centers_for_selector
  center_cycles :
    - all
  client_groups :
    - all
  client_verifications :
    - all
  clients :
    - index
    - new
    - create
    - bulk_entry
    - show
    - edit
    - update
  new_clients :
    - all
  documents :
    - all
  holiday_calendars :
    - all
  holidays :
    - all
  lendings :
    - all
#    - index
#    - create
#   - create_repayment_on_lending
#    - show
#    - edit
#    - update
#    - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
#    - new
#    - lending_transactions
#    - payment_on_disburse_loan
#    - lending_due_statuses
  fee_instances :
     - fee_instance_on_lending
     - index
  loan_applications :
     - index
     - show
     - bulk_create_loan_applicant
     - bulk_create
     - list
     - bulk_new
     - edit
     - update
     - get_param_value
     - suspected_duplicates
     - get_de_dupe_loan_applications
     - record_suspected_duplicates
     - duplicate_record
#     - all
  loan_authorizations :
     - all
  loan_files :
     - index
     - show
     - get_data
     - generate_disbursement_sheet
     - generate_disbursement_labels
     - record_loan_file
     - loan_file_generation
     - get_param_value
     - pending_loan_file_generation
#     - all
#  overlap_report_requests:
#    - all
#  overlap_report_responses:
#    - all
  meeting_schedules :
    - all

  user_locations :
    - all
  searches :
    - all
  lending_products :
#    - all
     - index
     - show
#     - create
#     - new
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
  reports :
#    - show
#    - create
#    - edit
     - all
  center_cycles :
    - record_cgt
    - mark_cgt_grt
    - record_grt
  payment_transactions :
    - index
    - new
    - weeksheet_payments
    - create_group_payments
    - payment_form_for_lending
 # book_keeping :
 #   - all
  ledgers :
 #   - all
    - show
  money_deposits :
    - index
    - create
#     - mark_verification
#     - record_verification
    - get_bank_branches
    - get_bank_accounts
  location_holidays :
    - all
  simple_insurance_policies :
#    - all
    - show
#################
support :
  admin :
    - index
    - show
  home :
    - all
  browse :
    - all
  accounting_rules :
    - index
    - show
#  asset_register :
#     - all
#    - index
#    - new
#    - create
#    - edit
#    - update
#   - show

  attendances :
    - index
    - create
  staff_attendances :
  audit_trails:
    - all
    - index
    - show
  book_keeping :
    - all
#  center_cycles :
#    - all
  client_groups :
    - all
  client_verifications :
    - all
  new_clients :
#   - index
    - show
  clients :
    - index
    - new
    - create
    - bulk_entry
    - show
#  documents :
#    - all
#  holiday_calendars :
#    - all
#  ledgers :
#    - index
#   - show
  lendings :
    - index
    - create
    - create_repayment_on_lending
    - show
    - edit
    - update
    - update_lending_approve_to_disburse
    - update_lending_new_to_approve
  loan_applications :
    - index
    - show
#   - bulk_create_loan_applicant
#   - bulk_create
    - list
    - bulk_new
#   - edit
    - update
    - get_param_value
    - suspected_duplicates
    - get_de_dupe_loan_applications
    - record_suspected_duplicates
    - duplicate_record
#   - all
  loan_files :
    - index
    - show
    - get_data
    - generate_disbursement_sheet
    - generate_disbursement_labels
#   - record_loan_file
#   - loan_file_generation
    - get_param_value
#   - all
  reports :
    - index
    - show
    - get_dates
    - get_date
  searches :
    - all
  user_locations :
    - all
  biz_locations :
    - centers_for_selector
    - show
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
################
finops :
  home :
    - all
  browse :
    - all
  admin :
    - index
#  accounting_rules :
#    - all
#    - index
#    - show
  ledgers :
    - all
#  vouchers :
#    - all
#  cost_centers :
#    - all
#  transaction_summaries :
#    - all
#  accounting_rules :
#    - all

#  asset_register :
#    - index
#    - new
#    - create
#    - edit
#    - update
    - show
#  attendances :
#    - index
#    - create
  staff_attendances :
  audit_trails :
    - index
    - show
  biz_locations :
#    - index
#    - create
#    - edit
#    - update
#    - show
    - centers_for_selector
 # book_keeping :
 #   - all
#  center_cycles :
#    - all
  client_groups :
    - all
#  client_verifications :
#    - all
  new_clients :
 #    - index
     - show
     - create_clients_for_loan_file
     - create_client_for_selected_loan_application
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
#    - edit
#    - update
#  designations :
#    - all
#  document_types :
#    - all
  documents :
    - all
  funders :
    - index
    - show
    - funding_lines

  funding_lines :
    - index
    - show
    - redirect_to_show
    - get_context
  lending_products :
 #   - index
    - show

  lendings :
#    - index
#    - create
#    - create_repayment_on_lending
    - show
#    - edit
#    - update
  loan_applications :
    - index
    - show
#   - bulk_create_loan_applicant
#   - bulk_create
    - list
#    - bulk_new
    - edit
    - update
    - get_param_value
    - suspected_duplicates
    - get_de_dupe_loan_applications
    - record_suspected_duplicates
    - duplicate_record
  overlap_report_requests:
    - all
  overlap_report_responses:
    - all
#  loan_purposes :
#    - all
  searches :
    - all
  loan_files :
#    - index
    - show
#    - get_data
    - generate_disbursement_sheet
    - generate_disbursement_labels
#    - record_loan_file
#    - loan_file_generation
    - get_param_value
    - record_health_check_status
    - generate_loans
    - show_loan_files
#  loan_authorizations :
#    - all
  reports :
    - all
#    - index
#    - show
#    - get_dates
#    - get_date
  center_cycles :
    - record_cgt
    - mark_cgt_grt
#    - record_grt
  user_locations :
    - all
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
#  money_deposits :
#    - index
#     - create
#    - mark_verification
#    - record_verification
#     - get_bank_branches
#     - get_bank_accounts
################
read_only :
  home :
    - all
  browse :
    - all
  accounting_rules :
    - index
    - show
  admin :
    - index
  asset_register :
#     - all
    - index
#    - new
#    - create
#    - edit
#    - update
    - show

#  attendances :
#    - index
#    - create
  staff_attendances :
  audit_trails:
#    - all
    - index
    - show
  biz_locations:
    - show
#  book_keeping :
#    - all
#  center_cycles :
#    - all
#  client_groups :
#    - all
#  client_verifications :
#    - all
  new_clients :
    - show
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
  user_locations :
    - all
  documents :
    - all
#  holiday_calendars :
#    - all
#  ledgers :
#    - index
#   - show
  lendings :
    - index
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale

#    - create
#    - create_repayment_on_lending
    - show
#    - edit
#    - update
#   - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
#    - lending_accrual_transaction
#  loan_applications :
#   - index
#    - show
#   - bulk_create_loan_applicant
#   - bulk_create
#    - list
#    - bulk_new
#   - edit
#    - update
#    - get_param_value
#    - suspected_duplicates
#    - get_de_dupe_loan_applications
#    - record_suspected_duplicates
#   - all
#  loan_files :
#    - index
#    - show
#    - get_data
#    - generate_disbursement_sheet
#    - generate_disbursement_labels
#   - record_loan_file
#   - loan_file_generation
#    - get_param_value
#   - all
  reports :
    - index
    - show
#    - get_dates
#    - get_date
  searches :
    - all
##########3
accountant :
  home :
    - all
  browse :
    - all
  admin :
    - index
  asset_register :
     - all
#    - index
#    - new
#    - create
#    - edit
#    - update
#    - show
#  attendances :
#    - index
#    - create
  staff_attendances :
  audit_trails:
    - index
    - show
  biz_locations:
 #   - all
    - create_and_assign_location
    - map_locations
    - show
    - create
#    - index
    - biz_location_clients
    - biz_location_form
    - centers_for_selector
#  center_cycles :
#    - all
#  client_groups :
#    - all
  client_groups :
    - all
#  client_verifications :
#    - all
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
#    - edit
#    - update
  new_clients :
#    - all
    - index
    - show_accounts
    - show
#    - new
#  documents :
#    - all
#  holiday_calendars :
#    - all
#  holidays :
#    - all
  lendings :
#    - all
#    - index
#    - create
#   - create_repayment_on_lending
    - show
#    - edit
#    - update
#    - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
#    - new
#    - lending_transactions
#    - payment_on_disburse_loan
    - lending_due_statuses
    - lending_accrual_transaction
    - lending_status_history
#  loan_applications :
#     - index
#     - show
#     - bulk_create_loan_applicant
#     - bulk_create
#     - list
#     - bulk_new
#     - edit
#     - update
#     - get_param_value
#     - suspected_duplicates
#     - get_de_dupe_loan_applications
#     - record_suspected_duplicates
#     - all
#  loan_authorizations :
#     - all
#  loan_files :
#     - index
#     - show
#     - get_data
#     - generate_disbursement_sheet
#     - generate_disbursement_labels
#     - record_loan_file
#     - loan_file_generation
#     - get_param_value
#     - pending_loan_file_generation
#     - all
#  overlap_report_requests:
#    - all
#  overlap_report_responses:
#    - all
  user_locations :
#    - all
    - index
    - show
#    - meeting_schedule
#    - meeting_calendar
    - weeksheet_collection
    - customers_on_biz_location
    - loans_on_biz_location
#    - biz_location_list
    - staffs_on_biz_location
    - location_eod_summary
#    - pdf_on_biz_location
  searches :
    - all
#  lending_products :
#    - index
#    - show
  reports :
#    - show
#    - create
#    - edit
    - all
#  center_cycles :
#    - record_cgt
#    - mark_cgt_grt
#    - record_grt
#  payment_transactions :
#    - index
#    - new
#    - weeksheet_payments
#    - create_group_payments
  book_keeping :
    - all
  ledgers :
    - all
  vouchers :
    - all
  cost_centers :
    - all
  transaction_summaries :
    - all
  accounting_rules :
    - all
#  users :
#     - index
#    - show
#    - edit
#    - update
#     - change_password
#    - new
#    - admin_change_password
#    - preferred_locale
  money_deposits :
    - index
#     - create
    - mark_verification
    - record_verification
#     - get_bank_branches
#     - get_bank_accounts

##########
auditor :
  home :
    - all
  browse :
    - all
#  admin :
#    - index
#  asset_register :
#    - index
#    - new
#    - create
#    - edit
#    - update
#    - show
#  attendances :
#    - index
#    - create
  staff_attendances :
  audit_trails:
    - index
    - show
  biz_locations:
 #   - all
    - create_and_assign_location
    - map_locations
    - show
    - create
#    - index
    - biz_location_clients
    - biz_location_form
    - centers_for_selector
#  center_cycles :
#    - all
#  client_groups :
#    - all
  client_groups :
    - all
#  client_verifications :
#    - all
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
#    - edit
#    - update
  new_clients :
#    - all
    - index
    - show_accounts
    - show
#    - new
  documents :
    - all
#  holiday_calendars :
#    - all
#  holidays :
#    - all
  lendings :
#    - all
#    - index
#    - create
#   - create_repayment_on_lending
    - show
#    - edit
#    - update
#    - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
#    - new
#    - lending_transactions
#    - payment_on_disburse_loan
    - lending_due_statuses
    - lending_accrual_transaction
    - lending_status_history
#  loan_applications :
#     - index
#     - show
#     - bulk_create_loan_applicant
#     - bulk_create
#     - list
#     - bulk_new
#     - edit
#     - update
#     - get_param_value
#     - suspected_duplicates
#     - get_de_dupe_loan_applications
#     - record_suspected_duplicates
#     - all
#  loan_authorizations :
#     - all
#  loan_files :
#     - index
#     - show
#     - get_data
#     - generate_disbursement_sheet
#     - generate_disbursement_labels
#     - record_loan_file
#     - loan_file_generation
#     - get_param_value
#     - pending_loan_file_generation
#     - all
#  overlap_report_requests:
#    - all
#  overlap_report_responses:
#    - all
  user_locations :
#    - all
    - index
    - show
#    - meeting_schedule
#    - meeting_calendar
    - weeksheet_collection
    - customers_on_biz_location
    - loans_on_biz_location
#    - biz_location_list
    - staffs_on_biz_location
    - location_eod_summary
#    - pdf_on_biz_location
  searches :
    - all
#  lending_products :
#    - index
#    - show
  reports :
#    - show
#    - create
#    - edit
    - all
#  center_cycles :
#    - record_cgt
#    - mark_cgt_grt
#    - record_grt
#  payment_transactions :
#    - index
#    - new
#    - weeksheet_payments
#    - create_group_payments
  book_keeping :
    - all
  ledgers :
    - all
  vouchers :
    - all
  cost_centers :
    - all
  transaction_summaries :
    - all
  accounting_rules :
    - all
#  users :
#     - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
  money_deposits :
    - index
#     - create
    - mark_verification
    - record_verification
#     - get_bank_branches
#     - get_bank_accounts
#########
telecaller :

  home :
    - all
  browse :
    - all
#  accounting_rules :
#    - index
#    - show
#  asset_register :
#     - all
#    - index
#    - new
#    - create
#    - edit
#    - update
#    - show

#  attendances :
#    - index
#    - create
#  audit_trails:
#    - all
#    - index
#    - show
  biz_locations:
    - show
#  book_keeping :
#    - all
#  center_cycles :
#    - all
#  client_groups :
#    - all
#  client_verifications :
#    - all
  new_clients :
    - show
  clients :
    - index
#    - new
#    - create
#    - bulk_entry
    - show
  staff_attendances :
  user_locations :
    - all
  documents :
    - all
#  holiday_calendars :
#    - all
#  ledgers :
#    - index
#   - show
  
#  users :
#   - index
#    - show
#    - edit
#    - update
#    - change_password
#     - new
#    - admin_change_password
#    - preferred_locale
  lendings :
    - index
#    - create
#    - create_repayment_on_lending
#    - show
#    - edit
#    - update
#   - update_lending_approve_to_disburse
#    - update_lending_new_to_approve
    - lending_accrual_transaction
#  loan_applications :
#   - index
#    - show
#   - bulk_create_loan_applicant
#   - bulk_create
#    - list
#    - bulk_new
#   - edit
#    - update
#    - get_param_value
#    - suspected_duplicates
#    - get_de_dupe_loan_applications
#    - record_suspected_duplicates
#   - all
#  loan_files :
#    - index
#    - show
#    - get_data
#    - generate_disbursement_sheet
#    - generate_disbursement_labels
#   - record_loan_file
#   - loan_file_generation
#    - get_param_value
#   - all
#  reports :
#    - index
#    - show
#    - get_dates
#    - get_date
#  searches :
#    - all
