---
loan_disbursement:
  debit:
    loan_disbursed: customer_loan_disbursed
  credit:
    total_paid: customer_cash
loan_repayment:
  debit:
    total_received: customer_cash
  credit:
    principal_received: customer_loan_debtors
    interest_received: customer_loan_interest_receipt
    advance_received: customer_loan_advance_receipt
loan_preclosure:
  debit:
    total_received: customer_cash
  credit:
    principal_received: customer_loan_debtors
    interest_received: customer_loan_interest_receipt
loan_advance_adjustment:
  debit:
    advance_adjusted: customer_loan_advance_receipt
  credit:
    principal_received: customer_loan_debtors
    interest_received: customer_loan_interest_receipt
loan_recovery:
  debit:
    total_received: customer_cash
  credit:
    total_received: customer_loan_other_income    
loan_accrue_regular_principal:
  debit:
    total_accrued: customer_loan_debtors
  credit:
    total_accrued: customer_loan_disbursed
loan_accrue_regular_interest:
  debit:
    total_accrued: customer_loan_debtors
  credit:
    total_accrued: customer_loan_interest_receipt
loan_accrue_broken_period_interest:
  debit:
    total_accrued: customer_loan_debtors
  credit:
    total_accrued: customer_loan_interest_receipt
loan_accrue_broken_period_interest_reversal:
  debit:
    total_accrued: customer_loan_interest_receipt
  credit:
    total_accrued: customer_loan_debtors
loan_fee_receipt:
  debit:
    total_received: customer_cash
  credit:
    total_received: customer_loan_fee_receipt
