module Constants
  module Loan
    
    DISBURSEMENT = :disbursement; REPAYMENT = :repayment
    LOAN_PAYMENT_TYPES = [ DISBURSEMENT, REPAYMENT ]

    NOT_APPLICABLE = :not_applicable; NOT_DUE = :not_due; DUE = :due; OVERDUE = :overdue
    LOAN_DUE_STATUSES = [ NOT_APPLICABLE, NOT_DUE, DUE, OVERDUE ]

    ADMINISTERED_AT = :administered_at
    ACCOUNTED_AT    = :accounted_at

    DISBURSE_LOAN_ACTION = :disburse_loan_action; REPAY_LOAN_ACTION = :repay_loan_action
    NOT_SPECIFIED = 'Not Specified'; CASH = 'Cash'; CHEQUE = 'Cheque'
    DISBURSEMENT_MODES = [NOT_SPECIFIED, CASH, CHEQUE]
    LOAN_ACTIONS = [ DISBURSE_LOAN_ACTION, REPAY_LOAN_ACTION ]

    INTEREST_RATE_PRECISION = 65
    INTEREST_RATE_SCALE = 2

    DEATH_EVENT_MARKED = :death_event_marked
    DEFAULT_LOAN_CLAIM_PROCESSING_STATUS = DEATH_EVENT_MARKED
    LOAN_CLAIM_PROCESSING_STATUSES = [DEATH_EVENT_MARKED]

    CLOSED_AGAINST_CLAIM_PROCEEDS = :closed_against_claim_proceeds
    CLAIM_PROCESSING_NOT_COMPLETED = :claim_processing_not_completed
    DEFAULT_LOAN_CLAIM_PROCESSING_COMPLETION_STATUS = CLAIM_PROCESSING_NOT_COMPLETED
    LOAN_CLAIM_PROCESSING_COMPLETION_STATUSES = [CLAIM_PROCESSING_NOT_COMPLETED, CLOSED_AGAINST_CLAIM_PROCEEDS]
    
  end
end
